### ISSUE TITLE
code extension?

### ISSUE THREAD

**Issue by RichardShea** [HongtengXu/SGWB-Graphon#1]
Hi, 

Can (or does) this code be applied to your "Hawkes Processes on Graphons" paper?  Or is there a separate repo?

Thank you,

-Richard

**Comment by HongtengXu** [comment]
> Hi,
> 
> Can (or does) this code be applied to your "Hawkes Processes on Graphons" paper? Or is there a separate repo?
> 
> Thank you,
> 
> -Richard

Hi, Richard. Sorry for replying late. The "Hawkes Processes on Graphons" is still under development (and under review). We plan to release the code by a separate repo when the work is accepted by somewhere. Thanks.
