### ISSUE TITLE
Varying sized graphs

### ISSUE THREAD

**Issue by xinyue96** [HongtengXu/SGWB-Graphon#2]
Hi,

Thank you so much for sharing your code. I was running your code to reproduce the synthetic experiment results in your paper.
Interestingly, for the case of varying sized graphs, I found that your code produced much lower error (mean and variance) value for GWB and SGWB than those reported in your paper. Any insight why that happened?

Thank you.

**Comment by HongtengXu** [comment]
> Hi,
> 
> Thank you so much for sharing your code. I was running your code to reproduce the synthetic experiment results in your paper. Interestingly, for the case of varying sized graphs, I found that your code produced much lower error (mean and variance) value for GWB and SGWB than those reported in your paper. Any insight why that happened?
> 
> Thank you.

Hi, I think it is possible... Firstly, I did not set a random seed in my code, which may introduce more randomness. Secondly, the standard deviation shown in the paper indicates that in some cases, the variance of the results is large. Maybe adding the number of trials can help. Thirdly, both GWB and SGWB are nonconvex optimization problems, whose stationary points may be different when the initialization, the input graphs, and the hyperparameters change. Anyway, I think a lower error is possible.
